### ISSUE TITLE
Create Presentation

### ISSUE THREAD

**Issue by LyubimaMalkocheva** [yoannary/figma-project-influencerai#2]

**Comment by LyubimaMalkocheva** [comment]
- Intoduction to InfluencerAi
- Competitor Analysis
- User Persona
- WebSite map / architecture
- Low level sketches
- Why InfluencerAI
- Add link for figma project

**Comment by yoannary** [comment]
![Image](https://github.com/yoannary/figma-project-influencerai/assets/118536360/98b3fd05-2c86-439c-b95a-a68892ef7a8d)

**Comment by yoannary** [comment]
- Шрифт
- Лого
- Нбу, факултетните номера имената
- Комп. анализ добавя
- Тумно сини букви

**Comment by LyubimaMalkocheva** [comment]
https://docs.google.com/presentation/d/1hZpJw3XW6ck6YoefMBCEfgDC0oJHDo9k/edit?usp=sharing&ouid=101705106915754165807&rtpof=true&sd=true

**Comment by yoannary** [comment]
- analysis 
- site map
- wireframe

**Comment by yoannary** [comment]
Линк към concurrent analysis за презентацията
https://workspace6705640.xtensio.com/ffwyeh94
