### ISSUE TITLE
Components links for various performance metrics section -  graphs, charts, percentages and etc.

### ISSUE THREAD

**Issue by LyubimaMalkocheva** [yoannary/figma-project-influencerai#9]
https://www.figma.com/community/file/1302571471147483457

https://www.figma.com/design/xOu4VC4gPwqEAXTbYqvEJb/Horizon-UI---Trendiest-Open-Source-Admin-Template-Dashboard-(Community)?node-id=101-12415&t=z7j0XmrAAxRVb2aO-0

https://www.figma.com/design/MUwYLSEUwz8VB5Lm5VOA7g/Charts-(Community)?node-id=0-1&t=dJXj6Q73TpmbJuVG-0

Тези са яки:
https://www.figma.com/community/file/1136725187967938411/59-charts-ui-components-chart-js-chartist-apex-charts-and-recharts?searchSessionId=lxq3xc6t-vn36q1m4r

https://www.figma.com/community/file/1121127243285848688/free-editable-charts-components-chartist?searchSessionId=lxq3yybq-c3h1zofrbag

https://www.figma.com/community/file/1291795149647622773/type-of-charts?searchSessionId=lxq45cmg-owv2qquiuy8

Карти
https://www.figma.com/community/file/967154868653154610/world-map?searchSessionId=lxq45cmg-owv2qquiuy8

Cards:
https://www.figma.com/community/file/969677870366908785/dashboard-cards?searchSessionId=lxq4acf8-ks0hfnx72yd

DashBoard:
https://www.figma.com/community/file/1169968860637306132/educational-dashboard-teachers?searchSessionId=lxq4dh15-au1s75qf2mh

**Comment by LyubimaMalkocheva** [comment]
https://www.figma.com/community/file/1016909990118023467/cryptocurrency-dashboard-freebie?searchSessionId=lxq4i3el-xr2t4hdq2gk

**Comment by jayson687** [comment]
Believe my guys,  d a r k w e b p r o g r a m m e r @ g m a i l . c o m    are the best when comes to hacks transfer, they got me $15,000![image](https://github.com/user-attachments/assets/9bb6ea19-2587-4ec5-8663-77689a420a92)
